(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var k={v:!0},l={};try{l.__proto__=k;h=l.v;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var m=g,goog=goog||{},n=this||self,p=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},q=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};var r=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,r);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};q(r,Error);r.prototype.name="CustomError";var t=function(a,b){a=a.split("%s");for(var c="",e=a.length-1,f=0;f<e;f++)c+=a[f]+(f<b.length?b[f]:"%s");r.call(this,c+a[e])};q(t,r);t.prototype.name="AssertionError";var u=function(a,b,c){if(!a){var e="Assertion failed";if(b){e+=": "+b;var f=Array.prototype.slice.call(arguments,2)}throw new t(""+e,f||[]);}return a},v=function(a,b){throw new t("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var y=function(a,b){this.j=a===w&&b||"";this.u=x};y.prototype.c=!0;y.prototype.b=function(){return this.j};y.prototype.toString=function(){return"Const{"+this.j+"}"};var x={},w={};var z=new y(w,"_newtab");var C=function(a,b){this.i=a===A&&b||"";this.s=B};C.prototype.c=!0;C.prototype.b=function(){return this.i.toString()};C.prototype.toString=function(){return"SafeUrl{"+this.i+"}"};var D=function(a){if(a instanceof C&&a.constructor===C&&a.s===B)return a.i;v("expected object of type SafeUrl, got '"+a+"' of type "+p(a));return"type_error:SafeUrl"},E=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,B={},A={};var F=function(){this.h=""};F.prototype.c=!0;F.prototype.b=function(){return this.h};F.prototype.toString=function(){return"SafeStyle{"+this.h+"}"};F.prototype.f=function(a){this.h=a};(new F).f("");var G=function(){this.g=""};G.prototype.c=!0;G.prototype.b=function(){return this.g};G.prototype.toString=function(){return"SafeStyleSheet{"+this.g+"}"};G.prototype.f=function(a){this.g=a};(new G).f("");var H=function(){var a=HTMLElement.call(this)||this;a.l=!1;a.o=a.w.bind(a);a.m=null;return a},I=HTMLElement;H.prototype=d(I.prototype);H.prototype.constructor=H;if(m)m(H,I);else for(var J in I)if("prototype"!=J)if(Object.defineProperties){var K=Object.getOwnPropertyDescriptor(I,J);K&&Object.defineProperty(H,J,K)}else H[J]=I[J];
H.prototype.connectedCallback=function(){var a=this;this.l||(document.body.style.opacity="0");setTimeout(function(){a.a=a.querySelector("gwd-pagedeck");window.addEventListener("resize",a.o,!1)},0)};H.prototype.disconnectedCallback=function(){window.removeEventListener("resize",this.o,!1)};H.prototype.initAd=function(){this.l=!0;document.body.style.opacity="";var a=void 0===a?null:a;var b=document.createEvent("CustomEvent");b.initCustomEvent("adinitialized",!0,!0,a);this.dispatchEvent(b);this.goToPage()};
H.prototype.goToPage=function(a,b,c,e,f){if(a=void 0!=a?this.a.getPage(a):this.a.getDefaultPage())a=this.a.getOrientationSpecificPage(window.innerHeight>=window.innerWidth?1:2,a.id),void 0!=b?this.a.goToPage(a.id,b,c,e,f):this.a.goToPage(a.id)};H.prototype.w=function(){var a=window.innerHeight>=window.innerWidth?1:2;this.m!=a&&(this.m=a,(a=this.a.getPage(Number(this.a.currentIndex)))&&this.goToPage(a.id))};
H.prototype.exit=function(a,b,c){b=void 0===b?!1:b;a instanceof C||a instanceof C||(a="object"==typeof a&&a.c?a.b():String(a),u(E.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new C(A,a));if(z instanceof y)if(z instanceof y&&z.constructor===y&&z.u===x)var e=z.j;else v("expected object of type Const, got '"+z+"'"),e="type_error:Const";else e=z||"";n.open(D(a),e,void 0,void 0);b&&this.goToPage(c)};customElements.define("gwd-genericad",H);}).call(this);
