(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e,f="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var k={a:!0},l={};try{l.__proto__=k;h=l.a;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var m=g,n=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},p=n(this),q=this||self,r=Date.now||function(){return+new Date},t=function(a,b){a=a.split(".");var c=q;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&
c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};var u=function(){this.v=""};u.prototype.toString=function(){return"SafeStyle{"+this.v+"}"};u.prototype.l=function(a){this.v=a};(new u).l("");var v=function(){this.u=""};v.prototype.toString=function(){return"SafeStyleSheet{"+this.u+"}"};v.prototype.l=function(a){this.u=a};(new v).l("");Object.freeze&&Object.freeze([]);try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var w=function(a,b){var c=(c=q.performance)&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):r();a={label:a,type:9,value:c};b=b.google_js_reporting_queue=b.google_js_reporting_queue||[];2048>b.length&&b.push(a)};var x={},y=!1,z=!1;x.A=function(a){y||(y=!0,w("11",a))};x.B=function(a){z||(z=!0,w("12",a))};x.s=function(a,b,c){var d=b;d=void 0===d?q:d;if(d=(d=d.performance)&&d.now?d.now():null)a={label:a,type:void 0===c?0:c,value:d},b=b.google_js_reporting_queue=b.google_js_reporting_queue||[],2048>b.length&&b.push(a)};x.reset=function(a){z=y=!1;(a.google_js_reporting_queue=a.google_js_reporting_queue||[]).length=0};t("gwd.rumUtil",x);t("gwd.rumUtil.logContentLoading",x.A);
t("gwd.rumUtil.logContentRendered",x.B);t("gwd.rumUtil.logTimingEvent",x.s);t("gwd.rumUtil.reset",x.reset);var A=function(a){(0,x.s)("gwd3dmodel_"+(a?"start":"stop")+"Timer_TimeToFirstFrame",window);a?Enabler.startTimer("TimeToFirstFrame"):Enabler.stopTimer("TimeToFirstFrame")},C=function(a){a?Enabler.startTimer("TotalEngagement"):Enabler.stopTimer("TotalEngagement");B()},D=0,E=0;function B(){var a=Math.floor(performance.now()/100);0==D&&(D=a);for(a-=D;E<=a;E++)Enabler.counter("TotalSessionDurationDeciseconds",!0)}
var F={Engagement:function(){Enabler.reportEngagement()},Zoom:function(){Enabler.counter("Zoom",!0)},Pan:function(){Enabler.counter("Pan",!0)},Rotate:function(){Enabler.counter("Rotate",!0)},Hotspot1Click:function(){Enabler.counter("Hotspot1Click",!0)},Hotspot2Click:function(){Enabler.counter("Hotspot2Click",!0)},Hotspot3Click:function(){Enabler.counter("Hotspot3Click",!0)},Hotspot4Click:function(){Enabler.counter("Hotspot4Click",!0)},Hotspot5Click:function(){Enabler.counter("Hotspot5Click",!0)}},
G={};var H=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)};var I=["glass","gesture-cue-icon","gesture-cue-text","src","transparent"],J=function(){var a=HTMLElement.call(this)||this;a.h=null;a.j=!1;return a},K=HTMLElement;J.prototype=f(K.prototype);J.prototype.constructor=J;if(m)m(J,K);else for(var L in K)if("prototype"!=L)if(Object.defineProperties){var M=Object.getOwnPropertyDescriptor(K,L);M&&Object.defineProperty(J,L,M)}else J[L]=K[L];
J.prototype.connectedCallback=function(){window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));N(this)};
J.prototype.disconnectedCallback=function(){window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));this.i&&(clearTimeout(this.i),this.i=void 0)};J.prototype.attributeChangedCallback=function(){N(this)};
J.prototype.handleEvent=function(a){var b=this,c=a.type,d=a.detail;switch(c){case "click":(this.o||this.m)&&a.target===this.f&&a.stopPropagation();break;case "start-timer":case "stop-timer":O(this,d.timer,"start-timer"===c);break;case "scene-rendered":case "camera-changed":a.stopPropagation();H(c,this,d);break;case "hotspot-clicked":this.m=!0;window.setTimeout(function(){b.m=!1},0);P(d.index);a.stopPropagation();H(c,this,d);break;case "increment-counter":Q(d.counter,d.cumulative);break;case studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH:R(this).removeAttribute("scroll-gating");
Enabler.reportEngagement();B();break;case studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH:R(this).setAttribute("scroll-gating",""),B()}};
var R=function(a){a.f||(a.f=a.ownerDocument.createElement("gltf-viewer"),a.f.setAttribute("scroll-gating",""),a.f.addEventListener("start-timer",a),a.f.addEventListener("stop-timer",a),a.f.addEventListener("increment-counter",a),a.f.addEventListener("scene-rendered",a),a.f.addEventListener("camera-changed",a),a.f.addEventListener("hotspot-clicked",a),a.f.addEventListener("click",a),a.appendChild(a.f));return a.f},N=function(a){a.i||(a.i=window.setTimeout(a.gwdLoad.bind(a),0))};
J.prototype.gwdLoad=function(){this.i&&(clearTimeout(this.i),this.i=void 0);var a=this.f?this.f.getAttribute("src"):null,b=S(this,"src",!0);if(b){if(S(this,"transparent"),S(this,"glass"),b!==a&&(this.j=!1,this.classList.remove("ready"),A(!0)),this.h&&this.h.parentNode&&this.h.parentNode.removeChild(this.h),b=this.getAttribute("gesture-cue-icon")){this.h=this.ownerDocument.createElement("div");this.h.classList.add("gesture-cue-container");a=this.ownerDocument.createElement("div");a.classList.add("gesture-cue-icon");
a.style.backgroundImage='url("'+b+'")';b=parseFloat(this.getAttribute("gesture-cue-duration"));isFinite(b)||(b=29);a.style.animationIterationCount=0>b?"infinite, 1":(b/2).toFixed(1)+", 1";this.h.appendChild(a);if(a=this.getAttribute("gesture-cue-text"))b=this.ownerDocument.createElement("p"),b.classList.add("gesture-cue-text"),b.textContent=a,this.h.appendChild(b);this.appendChild(this.h)}}else T(this)};J.prototype.gwdIsLoaded=function(){return this.j};
var S=function(a,b,c){c=void 0===c?!1:c;var d=a.getAttribute(b);null==d||c&&!d?a.f&&a.f.removeAttribute(b):R(a).setAttribute(b,d);return a.f?a.f.getAttribute(b):null},T=function(a){a.j||(a.j=!0,H("ready",a))},O=function(a,b,c){c?"TotalEngagement"===b&&(a.o=!0,C(!0),H("interaction-start",a),a.h&&a.h.parentNode&&a.h.parentNode.removeChild(a.h)):"TotalEngagement"===b?(a.o=!1,C(!1),H("interaction-end",a)):"TimeToFirstFrame"===b&&(A(!1),a.classList.add("ready"),T(a))},Q=function(a,b){b=b?F:G;if(b[a])b[a]()},
P=function(a){F.Engagement();a="Hotspot"+(a+1)+"Click";if(F[a])F[a]()};e=J.prototype;e.setYaw=function(a){U(this,{name:"setYaw",yawAngle:a,pauseRestingAnimation:!0})};e.setTargetYaw=function(a){U(this,{name:"setTargetYaw",yawAngle:a})};e.setTargetPitch=function(a){U(this,{name:"setTargetPitch",pitchAngle:a})};e.incrementTargetPitch=function(a){U(this,{name:"incrementTargetPitch",pitchAngle:a})};e.setTargetZoom=function(a){U(this,{name:"setTargetZoom",scale:a})};
e.incrementTargetZoom=function(a){U(this,{name:"incrementTargetZoom",scale:a})};e.setTargetPivot=function(a,b,c){U(this,{name:"setTargetPivot",X:a,Y:b,Z:c})};e.setTargetLocalPan=function(a,b){U(this,{name:"setTargetLocalPan",X:a,Y:b})};e.setMaterialColor=function(a,b,c,d){U(this,{name:"setMaterialColor",material:a,r:b,g:c,b:d})};e.setMaterialClearCoat=function(a,b,c){U(this,{name:"setMaterialClearCoat",material:a,value:b,roughness:c})};e.playAnimation=function(a){U(this,{name:"animationPlay",animationName:a})};
e.pauseAnimation=function(a){U(this,{name:"animationPause",animationName:a})};e.setAnimationTime=function(a,b){U(this,{name:"animationSetTime",animationName:a,time:b})};e.incrementAnimationTime=function(a,b){U(this,{name:"animationIncrementTime",animationName:a,time:b})};e.addHotspot=function(a,b,c,d){U(this,{name:"addHotspot",hotspotName:a,x:b,y:c,z:d})};e.setHotspotInfoCard=function(a,b,c){U(this,{name:"setHotspotInfoCard",hotspotName:a,title:b,text:c})};
e.lookAtHotspot=function(a){U(this,{name:"lookAtHotspot",hotspotName:a})};e.lookAtHotspotIndex=function(a){U(this,{name:"lookAtHotspotIndex",hotspotIndex:a})};e.handleMessage=function(a){U(this,a)};var U=function(a,b){a=R(a);a.handleMessage&&a.handleMessage(b)};p.Object.defineProperties(J,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return I}}});customElements.define("gwd-3d-model",J);}).call(this);
