(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var l,m="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},p;if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var q;a:{var r={B:!0},t={};try{t.__proto__=r;q=t.B;break a}catch(a){}q=!1}p=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var u=p,v=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},w=v(this);var x=function(a,b,c){switch(a.getAttribute(b)){case "true":return!0;case "false":return!1;default:return c}};var y=/^(\d+|\d*\.\d+)px$/i,z=/^(\d+|\d*\.\d+)em$/i,A=function(){this.a=[];this.o=10;this.m=!0;this.A=!1};A.prototype.fit=function(a){var b=this;a.forEach(function(c){if(b.a.every(function(e){return e.element!=c})&&!c.hasAttribute("gwd-dont-fit")){var d=C(b,c);b.a.push(d)}})};
var E=function(a){a.a.forEach(function(b){D(b)});a.a=[]},F=function(a,b){b.forEach(function(c){for(var d=0;d<a.a.length;d++){var e=a.a[d];if(e.element==c){D(e);a.a.splice(d,1);break}}})},D=function(a){null!=a.u&&(a.element.style.fontSize=a.u);if(null!=a.j){for(;a.element.firstChild;)a.element.removeChild(a.element.lastChild);for(var b=a.j.cloneNode(!0);0<b.childNodes.length;)a.element.appendChild(b.firstChild)}},C=function(a,b){var c=window.getComputedStyle(b),d=b.style.fontSize,e=b.cloneNode(!0),
f={clientWidth:b.clientWidth,clientHeight:b.clientHeight},h=!1,g=a.m;b.hasAttribute("data-gwd-fit-font-size")&&(g="false"!=b.getAttribute("data-gwd-fit-font-size"));var k=G(c.fontSize);c=k||24;var n=parseInt(b.getAttribute("gwd-min-font-size-px"),10);n=isFinite(n)?n:a.o;g=g&&(!k||k>n)&&(b.scrollHeight>f.clientHeight||b.scrollWidth>f.clientWidth);k=!1;if(g){var B=G(window.getComputedStyle(b).fontSize);null!=B&&(h=H(a,b,B));c=I(b,f,n,c);-1==c?(b.style.fontSize=n+"px",k=!0):b.style.fontSize=c+"px"}c=
a.A;b.hasAttribute("gwd-fitting-truncate")&&(c="false"!=b.getAttribute("gwd-fitting-truncate"));c&&(k||b.scrollHeight>f.clientHeight||b.scrollWidth>f.clientWidth)&&(J(a,b,f,null),h=!0);return{element:b,u:g?d:null,j:h?e:null}},I=function(a,b,c,d){return K(a,b,c,d,function(e,f){e.style.fontSize=f+"px"})},J=function(a,b,c,d){if(d&&1!=d.nodeType&&3!=d.nodeType)return!1;var e=d?d:b;if(3==e.nodeType||0==e.children.length){var f=e.textContent;if(""==f)return!1;if(e!=b){e.textContent="\u2026";if(b.scrollHeight>
c.clientHeight||b.scrollWidth>c.clientWidth)return!1;e.textContent=f}a=K(b,c,0,f.length,function(g,k){e.textContent=f.slice(0,k)+"\u2026"});e.textContent=-1==a?"":f.slice(0,a)+"\u2026";return-1!=a}for(d=e.childNodes.length-1;0<=d;d--){var h=e.childNodes[d];if(J(a,b,c,h))return!0;e.removeChild(h)}return!1},K=function(a,b,c,d,e){d=Math.floor(d);for(var f=-1,h=0;50>h;){var g=Math.floor((c+d)/2);e(a,g);if(a.scrollHeight>b.clientHeight||a.scrollWidth>b.clientWidth){if(g==c)return f;d=g-1}else{f=g;if(c==
d)return f;c=g+1}h++}return-1},H=function(a,b,c){if(b.hasAttribute("gwd-dont-fit"))return!1;for(var d=!1,e=b.children.length,f=0;f<e;f++){var h=b.children[f],g=window.getComputedStyle(h).fontSize,k=G(g);if(k)h.style.fontSize=k/c+"em",d=!0;else if(g=(g=z.exec(g||""))?parseFloat(g[1]):null)k=g*c;else return!1;h=H(a,h,k);d=d||h}return d},G=function(a){return(a=y.exec(a||""))?parseFloat(a[1]):null};var L=function(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=window.setTimeout(function(){c=null;b&&(a(),b=!1)},100))}};var M="color font-family font-size font-style font-weight font-stretch text-align white-space".split(" "),N=/[^\s\xA0]/,O=function(a){this.w=a;this.g=new WeakMap;this.i=new WeakMap};O.prototype.saveInitialText=function(a){for(var b=document.createNodeIterator(a,NodeFilter.SHOW_TEXT,null,!1),c=null,d;d=b.nextNode();)if(N.test(d.textContent)){c=d;break}if(c&&(b=c.parentNode,b!=a)){a.setAttribute("gwd-dont-fit","");for(c=b;c.parentNode!=a;)c=c.parentNode;this.g.set(a,{f:c,parent:b})}};
O.prototype.applyStylePreservation=function(a){var b=this;if(this.g.get(a)){a.ownerDocument.compareDocumentPosition(a)&Node.DOCUMENT_POSITION_DISCONNECTED||P(this,a);var c=document.createElement("gwd-attached");a.appendChild(c);var d=function(){c.removeEventListener("attached",d);P(b,a);a.removeChild(c)};c.addEventListener("attached",d)}};
var P=function(a,b){var c=a.g.get(b),d=a.i.get(b)||{};if(c){c.f.style.display="none";b.insertBefore(c.f,b.firstChild);try{F(a.w,[b]);for(var e=getComputedStyle(c.parent),f=0;f<M.length;f++){var h=M[f],g=e.getPropertyValue(h);!d.hasOwnProperty(h)&&g&&b.style.setProperty(h,g,"")}b.removeAttribute("gwd-dont-fit");a.w.fit([b])}finally{b.removeChild(c.f)}}};O.prototype.saveStyleOverride=function(a,b,c){var d=this.i.get(a)||{};d[b]=c;this.i.set(a,d)};var Q=["data-gwd-fit-font-size","fit-font-size-for-selector","gwd-fitting-truncate","gwd-min-font-size-px"],R=function(){var a=HTMLElement.call(this)||this;a.b=new A;a.l=":not(*)";a.h=new O(a.b);a.s=a.F.bind(a);a.c=a.D.bind(a);a.v=L(a.C.bind(a));return a},S=HTMLElement;R.prototype=m(S.prototype);R.prototype.constructor=R;if(u)u(R,S);else for(var T in S)if("prototype"!=T)if(Object.defineProperties){var U=Object.getOwnPropertyDescriptor(S,T);U&&Object.defineProperty(R,T,U)}else R[T]=S[T];l=R.prototype;
l.connectedCallback=function(){document.addEventListener("pagetransitionstart",this.s);document.addEventListener("adinitialized",this.c)};l.disconnectedCallback=function(){document.removeEventListener("pagetransitionstart",this.s);document.removeEventListener("adinitialized",this.c);window.removeEventListener("resize",this.v,!1)};
l.attributeChangedCallback=function(a,b,c){switch(a){case "data-gwd-fit-font-size":this.b.m=x(this,a,!0);break;case "fit-font-size-for-selector":this.l=c||":not(*)";break;case "gwd-min-font-size-px":b=this.b;a=parseInt(this.getAttribute(a),10);isNaN(a)&&(a=10);b.o=a;break;case "gwd-fitting-truncate":this.b.A=x(this,a,!1)}};l.D=function(){document.removeEventListener("adinitialized",this.c);this.refitAll();window.addEventListener("resize",this.v,!1)};
l.F=function(a){"gwd-pagedeck"==a.target.tagName.toLowerCase()&&this.fit(V(this,a.target))};l.saveInitialText=function(a){this.h.saveInitialText(a)};l.applyStylePreservation=function(a){this.h.applyStylePreservation(a)};l.saveStyleOverride=function(a,b,c){this.h.saveStyleOverride(a,b,c)};l.fit=function(a){this.b.fit(a||V(this,document))};var V=function(a,b){return Array.prototype.slice.call(b.querySelectorAll(a.l)).filter(function(c){return c!==a})};R.prototype.C=function(){this.refitAll()};
R.prototype.refitAll=function(){E(this.b);this.fit()};w.Object.defineProperties(R,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return Q}}});customElements.define("gwd-text-helper",R);}).call(this);
