(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},f;if("function"==typeof Object.setPrototypeOf)f=Object.setPrototypeOf;else{var g;a:{var k={h:!0},l={};try{l.__proto__=k;g=l.h;break a}catch(a){}g=!1}f=g?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var n=f;var p=function(){var a=HTMLElement.call(this)||this;a.c="";a.a=null;a.b=[];a.g=!1;"function"!=typeof window.onAdData&&(a.g=!0,window.onAdData=a.onAdData_.bind(a));a.f=!1;return a},q=HTMLElement;p.prototype=d(q.prototype);p.prototype.constructor=p;if(n)n(p,q);else for(var r in q)if("prototype"!=r)if(Object.defineProperties){var t=Object.getOwnPropertyDescriptor(q,r);t&&Object.defineProperty(p,r,t)}else p[r]=q[r];
p.prototype.connectedCallback=function(){this.f||(this.c=this.getAttribute("id")+"_data",window[this.c]||(window[this.c]={}),this.f=!0)};p.prototype.getData=function(){if(this.hasAttribute("is-custom-schema")){var a={};window.dynamicContent?a=window.dynamicContent:window.devDynamicContent&&(a=window.devDynamicContent);u(this,a);return a}if(this.g)return this.a;a=Enabler.getParameter("AdData");return this.a=this.processAdData_(a)};p.prototype.isDataLoaded=function(){return!0};
p.prototype.addDataTransformer=function(a){this.b.push(a)};p.prototype.onAdData_=function(a){if(a){a=this.a=this.processAdData_(a);a=void 0===a?null:a;var b=document.createEvent("CustomEvent");b.initCustomEvent("ready",!0,!0,a);this.dispatchEvent(b)}};
p.prototype.processAdData_=function(a){if(!a)return null;a=a.google_template_data;if(!a)throw Error("Incorrect data format: missing google_template_data");a=a.adData;if(!a||!a.length)throw Error("Incorrect data format: missing google_template_data.adData");a=a[0];var b=this.hasAttribute("is-custom-schema");if(b)return window.dynamicContent=a;a=this.toCanonicalForm_(a);var c=this.getAttribute("network-schema-id");if(b)window.dynamicContent=a;else if(c&&416!=c&&311!=c){if(442==c){b=a.screenshots;if("undefined"==
typeof b){b=[];for(var e=1;4>=e;e++)(c=a["screenshot"+e])&&b.push(c);a.screenshots=b}"undefined"==typeof a.appIcon&&(b=a.appIconStandard,a.appIcon=a.appIconHighRes||b)}}else b=a.Design,Array.isArray(b)&&1==b.length&&(a.Design=b[0]),b=a.Headline,Array.isArray(b)&&1==b.length&&(a.Headline=b[0]);u(this,a);return a};var u=function(a,b){for(var c=0;c<a.b.length;c++)"function"==typeof a.b[c]&&a.b[c].call(a,b,a)};
p.prototype.toCanonicalForm_=function(a){var b={},c;for(c in a){var e=c.split("_");if(1==e.length)b[e[0]]=a[c];else{var h=e[0];var m=e[1];e=e[2];b[h]||(b[h]=[]);b[h][m]||(b[h][m]={});b[h][m][e]=a[c]}}return b};customElements.define("gwd-gpa-data-provider",p);}).call(this);
