(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e,f="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var l={B:!0},m={};try{m.__proto__=l;h=m.B;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=g,p=this||self,q=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},r=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};var t=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d};var u=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,u);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};r(u,Error);u.prototype.name="CustomError";var v=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,k=0;k<d;k++)c+=a[k]+(k<b.length?b[k]:"%s");u.call(this,c+a[d])};r(v,u);v.prototype.name="AssertionError";var w=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var k=Array.prototype.slice.call(arguments,2)}throw new v(""+d,k||[]);}return a},x=function(a,b){throw new v("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var A=function(a,b){this.l=a===y&&b||"";this.A=z};A.prototype.g=!0;A.prototype.f=function(){return this.l.toString()};A.prototype.toString=function(){return"SafeUrl{"+this.l+"}"};var B=function(a){if(a instanceof A&&a.constructor===A&&a.A===z)return a.l;x("expected object of type SafeUrl, got '"+a+"' of type "+q(a));return"type_error:SafeUrl"},C=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,z={},y={};var D=function(){this.j=""};D.prototype.g=!0;D.prototype.f=function(){return this.j};D.prototype.toString=function(){return"SafeStyle{"+this.j+"}"};D.prototype.h=function(a){this.j=a};(new D).h("");var E=function(){this.i=""};E.prototype.g=!0;E.prototype.f=function(){return this.i};E.prototype.toString=function(){return"SafeStyleSheet{"+this.i+"}"};E.prototype.h=function(a){this.i=a};(new E).h("");var F=[],G=function(a){a=F.indexOf(a);0<=a&&F.splice(a,1)};document.addEventListener("click",function(a){for(var b=0;b<F.length;b++)if(25>Math.abs(a.clientX-F[b].C)&&25>Math.abs(a.clientY-F[b].D)||25>Math.abs(a.screenX-F[b].J)&&25>Math.abs(a.screenY-F[b].K))F.splice(b,1),a.stopPropagation(),a.preventDefault()},!0);var H=function(){var a=HTMLElement.call(this)||this;a.v=0;a.w=0;a.c=null;a.o=null;a.b=null;a.m=null;a.s=a.F.bind(a);a.a=!0;return a},I=HTMLElement;H.prototype=f(I.prototype);
H.prototype.constructor=H;if(n)n(H,I);else for(var J in I)if("prototype"!=J)if(Object.defineProperties){var K=Object.getOwnPropertyDescriptor(I,J);K&&Object.defineProperty(H,J,K)}else H[J]=I[J];e=H.prototype;e.connectedCallback=function(){this.b||(this.c=this.u.bind(this),this.o=this.I.bind(this),this.b=this.H.bind(this),this.m=this.G.bind(this));this.addEventListener("click",this.c,!1);this.addEventListener("touchstart",this.o,!1);this.addEventListener("action",this.s,!1)};
e.disconnectedCallback=function(){this.removeEventListener("click",this.c,!1);this.removeEventListener("touchstart",this.o,!1);this.removeEventListener("action",this.s,!1)};e.u=function(a){this.a&&t("action",this,a);this.a=!0};e.I=function(a){this.addEventListener("touchmove",this.b,!1);this.addEventListener("touchend",this.m,!1);a=a.touches[0];this.v=a.clientX;this.w=a.clientY};
e.G=function(a){this.u(a);this.removeEventListener("touchmove",this.b,!1);this.removeEventListener("touchend",this.m,!1);a=a.changedTouches[0];a={C:a.clientX,D:a.clientY,J:a.screenX,K:a.screenY};F.push(a);setTimeout(G.bind(null,a),2500)};e.H=function(a){a=a.touches[0];this.a=this.a&&10>=Math.abs(this.v-a.clientX)&&10>=Math.abs(this.w-a.clientY)};
e.F=function(a){var b=this.getAttribute("exit-id"),c=this.getAttribute("product-index"),d=this.getAttribute("exit-override-url");d&&!t("tapareaexit",this,{"exit-id":b,url:d,"product-index":c,"action-event":a.detail}).detail.handled&&(d instanceof A?a=d:(a=d,a instanceof A||(a="object"==typeof a&&a.g?a.f():String(a),w(C.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new A(y,a))),p.open(B(a),"",void 0,void 0))};customElements.define("gwd-taparea",H);}).call(this);
